services:
  postgres-chess:
    image: postgres:16-alpine

  redis-chess:
    image: redis:7.2

  MyChess760:
    image: eclipse-temurin:21
    working_dir: /app
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ./mvnw spring-boot:run
    depends_on:
      postgres-chess:
        condition: service_healthy
      redis-chess:
        condition: service_healthy

volumes:
  maven_cache: