spring.application.name=MyChess760

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

#JWT
jwt.secret=${JWT_SECRET:myverylongsecretkeyatleast256bitslong}
jwt.expiration=${JWT_EXPIRATION:86400000}


# Logs
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chess}
spring.datasource.username=${POSTGRES_USER:chess}
spring.datasource.password=${POSTGRES_PASSWORD:chess}

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.docker.compose.enabled=false
spring.devtools.add-properties=false